kind: pipeline
type: docker
name: default
steps:
  - name: Build Image
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      registry: https://code.smartsheep.studio
      repo: code.smartsheep.studio/atom/stackcloud
      username: CD.Agent
      password:
        from_secret: CD.Agent
      auto_tag: true
