debug = true
instance_id = "72741cd3-0483-49e7-bacd-f103a1bc01d0"
base_url = "http://localhost:9444"
endpoints = "http://localhost:9443"
mount_key = "WGqNUFNhED"

[paths]
user_contents = "dist/uploads"

[security]
sessions_alive_duration = "720h"

[hypertext]
listen_addr = "0.0.0.0:9444"
max_body_size = 4194304
[http.advanced]
prefork = false

[datasource]
[datasource.master]
table_prefix = "stackcloud_"
dsn = "host=localhost user=postgres password=password dbname=stackcloud port=5432 sslmode=disable timezone=Asia/Shanghai"
