debug = true
instance_id = "b20b7a22-9bce-47b7-8560-52443d221711"
base_url = "http://localhost:9444"
endpoints = "http://localhost:9443"
mount_key = "WGqNUFNhED"

[paths]
user_contents = "dist/uploads"

[security]
sessions_alive_duration = "720h"

[http]
listen_addr = "0.0.0.0:9444"
max_body_size = 4194304
[http.advanced]
prefork = false

[datasource]
[datasource.master]
table_prefix = "stackcloud_"
dsn = "host=localhost user=postgres password=password dbname=stackcloud port=5432 sslmode=disable timezone=Asia/Shanghai"
